app/main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('fridge/', views.fridge, name='fridge'),
    path('fridge/add/', views.add_fridge, name='add-fridge'),
    path('fridge/add/<int:pk>/', views.input_date, name='input-date'),

    path('fridge/add/vegetables/', views.add_vegetable, name='add-vegetable'),
    path('fridge/add/meat/', views.add_meat, name='add-meat'),
    path('fridge/add/marine/', views.add_marine, name='add-marine'),
    path('fridge/add/grain/', views.add_grain, name='add-grain'),
    path('fridge/add/sauce/', views.add_sauce, name='add-sauce'),
    path('fridge/add/milk/', views.add_milk, name='add-milk'),
    path('fridge/add/others/', views.add_others, name='add-others'),

    path('fridge/delete/<int:pk>/', views.delete_fridge_ingredient, name='delete-fridge-ingredient'),

    path('memo/', views.memo, name='memo'),
    path('memo/add/', views.add_memo, name='add-memo'),
    path('memo/add/<int:pk>/', views.add_memo_ingredient, name='add-memo-ingredient'),
    path('memo/delete/<int:pk>/', views.delete_memo_ingredient, name='delete-memo-ingredient'),
    path('memo/check/<int:pk>/', views.memo_check, name='memo-check'),
    path('memo/check/clear/', views.memo_check_clear, name='memo-check-clear'),

    path('recommendation/', views.recommendation, name='recommendation'),
    path('recommendation/recipe/<int:pk>/', views.recipe, name='recipe'),
    path('recommendation/like/<int:pk>/', views.like, name='like'),

    path('blog/', views.blog, name='blog'),
]

app/main/models.py
import datetime

from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Ingredient(models.Model):
    FRIDGER = (
        ('F', 'Freezer'),
        ('R', 'Refrigerator'),
        ('T', 'Room Temperature')
    )
    TYPE = (
        ('vegetables', '채소/과일'),
        ('meat', '육류'),
        ('marine', '수산물'),
        ('grain', '곡물/견과류'),
        ('sauce', '양념/소스'),
        ('milk', '가공/유제품'),
        ('others', '기타'),
    )

    name = models.CharField(max_length=50)
    keeping_days = models.PositiveIntegerField()
    kcalories = models.PositiveIntegerField()
    image = models.ImageField(upload_to='images/ingredients/')
    fridger = models.CharField(max_length=2, choices=FRIDGER)
    type = models.CharField(choices=TYPE, max_length=10, null=True, blank=True)

    def __str__(self):
        return self.name


class MyStoredIngredient(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, blank=True, null=True)
    input_date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.ingredient.name

    def freshness(self):
        keeping_days = int(self.ingredient.keeping_days)
        keeping_date = self.input_date + datetime.timedelta(days=keeping_days)
        left = keeping_date - datetime.datetime.today().date()
        left_days = left.days

        if keeping_days - left_days <= keeping_days * 0.3:
            return '신선도 높음'
        elif keeping_days - left_days <= keeping_days * 0.7:
            return '신선도 보통'
        elif keeping_days - left_days <= keeping_days:
            return '신선도 낮음'
        return '신선도 위험'

    def left_days(self):
        keeping_days = int(self.ingredient.keeping_days)
        keeping_date = self.input_date + datetime.timedelta(days=keeping_days)
        left = keeping_date - datetime.datetime.today().date()
        left_days = left.days

        if keeping_days - left_days > keeping_days: return -left_days
        return left_days


class MyMemoIngredient(models.Model):
    STATUS = (
        ('checked', 'checked'),
        ('not_checked', 'not_checked'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS, max_length=20, default='not_checked')

    def __str__(self):
        return self.ingredient


class RecommendedFood(models.Model):
    TYPE = (
        ('broth', '육수'),
        ('vegetables', '채소'),
        ('marine', '해산물'),
        ('meat', '고기/계란'),
        ('rice', '밥/쌀'),
        ('kimchi', '김치/발효'),
        ('dessert', '간식/디저트'),
    )

    user = models.ManyToManyField(User)
    name = models.CharField(max_length=30)
    ingredients_detail = models.CharField(max_length=200)
    ingredient = models.ManyToManyField(Ingredient, blank=True)
    recipe = models.TextField()
    type = models.CharField(choices=TYPE, max_length=30)

    def __str__(self):
        return self.name

    def user_count(self):
        return len(self.user.all())


class FoodComment(models.Model):
    food = models.ForeignKey(RecommendedFood, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=300)
    created_at = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return self.food.name, self.user.nickname

    def created_date(self):
        today = datetime.date.today()
        date = today - self.created_at
        return f'{date.days}일 전'

app/main/urls/views.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('fridge/', views.fridge, name='fridge'),
    path('fridge/add/', views.add_fridge, name='add-fridge'),
    path('fridge/add/<int:pk>/', views.input_date, name='input-date'),

    path('fridge/add/vegetables/', views.add_vegetable, name='add-vegetable'),
    path('fridge/add/meat/', views.add_meat, name='add-meat'),
    path('fridge/add/marine/', views.add_marine, name='add-marine'),
    path('fridge/add/grain/', views.add_grain, name='add-grain'),
    path('fridge/add/sauce/', views.add_sauce, name='add-sauce'),
    path('fridge/add/milk/', views.add_milk, name='add-milk'),
    path('fridge/add/others/', views.add_others, name='add-others'),

    path('fridge/delete/<int:pk>/', views.delete_fridge_ingredient, name='delete-fridge-ingredient'),

    path('memo/', views.memo, name='memo'),
    path('memo/add/', views.add_memo, name='add-memo'),
    path('memo/add/<int:pk>/', views.add_memo_ingredient, name='add-memo-ingredient'),
    path('memo/delete/<int:pk>/', views.delete_memo_ingredient, name='delete-memo-ingredient'),
    path('memo/check/<int:pk>/', views.memo_check, name='memo-check'),
    path('memo/check/clear/', views.memo_check_clear, name='memo-check-clear'),

    path('recommendation/', views.recommendation, name='recommendation'),
    path('recommendation/recipe/<int:pk>/', views.recipe, name='recipe'),
    path('recommendation/recipe/<int:pk>/comment/', views.comment_create, name='comment-create'),
    path('recommendation/like/<int:pk>/', views.like, name='like'),

    path('store/', views.store, name='store'),
]

app/main/views.py
from django.shortcuts import render, redirect

from main.models import Ingredient, MyStoredIngredient, MyMemoIngredient, RecommendedFood


# sentry debug test
def trigger_error(request):
    division_by_zero = 1 / 0


# sentry CSP test web middleware
# type error (missing 1 required positional argument: 'response')
# def middleware(request, response):
#     response['Content-Security-Policy-Report-Only'] = \
#         "default-src 'self'; " \
#         f"report-uri {SECRETS['SENTRY_REPORT_URI']}"
#     return response


def start(request):
    return render(request, 'start.html')


def fridge(request):
    if request.user.is_authenticated:
        my_stored_ingredients = MyStoredIngredient.objects.filter(user=request.user)
        my_stored_ingredients_f, my_stored_ingredients_r, my_stored_ingredients_t = list(), list(), list()

        for my_stored_ingredient in my_stored_ingredients:
            if my_stored_ingredient.ingredient.fridger == 'F':
                my_stored_ingredients_f.append(my_stored_ingredient)
            elif my_stored_ingredient.ingredient.fridger == 'R':
                my_stored_ingredients_r.append(my_stored_ingredient)
            else:
                my_stored_ingredients_t.append(my_stored_ingredient)

        context = {
            'my_stored_ingredients': my_stored_ingredients,
            'my_stored_ingredients_f': my_stored_ingredients_f,
            'my_stored_ingredients_r': my_stored_ingredients_r,
            'my_stored_ingredients_t': my_stored_ingredients_t,
        }
        return render(request, 'main/fridge/fridge.html', context)
    return render(request, 'main/fridge/fridge.html')


def add_fridge(request):
    ingredients = Ingredient.objects.all().order_by('name')
    search_text = request.GET.get('search_text')

    if search_text != '' and search_text is not None:
        ingredients = ingredients.filter(name__contains=search_text)

    context = {
        'ingredients': ingredients,
    }
    return render(request, 'main/fridge/add_fridge.html', context)


def input_date(request, pk):
    ingredient = Ingredient.objects.get(pk=pk)
    print('ingredient.image.url >> ', ingredient.image.url)

    if request.method == 'POST':
        if MyStoredIngredient.objects.filter(user=request.user, ingredient=ingredient):
            error_msg = '이미 추가되어 있는 재료입니다.'
            previous_btn = '이전으로'
            context = {
                'ingredient': ingredient,
                'error_msg': error_msg,
                'previous_btn': previous_btn,
            }
            return render(request, 'main/fridge/input_date.html', context)

        date = request.POST['input_date']
        MyStoredIngredient.objects.create(input_date=date, user=request.user, ingredient=ingredient)
        return redirect('main:fridge')

    context = {
        'ingredient': ingredient,
    }
    return render(request, 'main/fridge/input_date.html', context)


def delete_fridge_ingredient(request, pk):
    my_stored_ingredient = MyStoredIngredient.objects.get(pk=pk)
    my_stored_ingredient.delete()
    return redirect('main:fridge')


def add_vegetable(request):
    return render(request, 'main/fridge/type/vegetables.html')


def add_meat(request):
    return render(request, 'main/fridge/type/meat.html')


def add_marine(request):
    return render(request, 'main/fridge/type/marine.html')


def add_grain(request):
    return render(request, 'main/fridge/type/grain.html')


def add_sauce(request):
    return render(request, 'main/fridge/type/sauce.html')


def add_milk(request):
    return render(request, 'main/fridge/type/milk.html')


def add_others(request):
    return render(request, 'main/fridge/type/others.html')


def memo(request):
    if request.user.is_authenticated:
        my_memo_ingredients = MyMemoIngredient.objects.filter(user=request.user)
        ingredients_not_checked, ingredients_checked, my_memo_ingredients_ve, my_memo_ingredients_me, my_memo_ingredients_ma, my_memo_ingredients_gr, my_memo_ingredients_sa, my_memo_ingredients_mi, my_memo_ingredients_ot = list(), list(), list(), list(), list(), list(), list(), list(), list()

        for my_memo_ingredient in my_memo_ingredients:
            if my_memo_ingredient.status == 'not_checked':
                ingredients_not_checked.append(my_memo_ingredient)
            else:
                ingredients_checked.append(my_memo_ingredient)

            if my_memo_ingredient.ingredient is not None:
                if my_memo_ingredient.ingredient.type == 'vegetables':
                    my_memo_ingredients_ve.append(my_memo_ingredient)
                elif my_memo_ingredient.ingredient.type == 'meat':
                    my_memo_ingredients_me.append(my_memo_ingredient)
                elif my_memo_ingredient.ingredient.type == 'marine':
                    my_memo_ingredients_ma.append(my_memo_ingredient)
                elif my_memo_ingredient.ingredient.type == 'grain':
                    my_memo_ingredients_gr.append(my_memo_ingredient)
                elif my_memo_ingredient.ingredient.type == 'sauce':
                    my_memo_ingredients_sa.append(my_memo_ingredient)
                elif my_memo_ingredient.ingredient.type == 'milk':
                    my_memo_ingredients_mi.append(my_memo_ingredient)
                else:
                    my_memo_ingredients_ot.append(my_memo_ingredient)

        not_checked_count = len(ingredients_not_checked)
        checked_count = len(ingredients_checked)
        all_count = len(my_memo_ingredients)

        if all_count:
            progress_percentage = int((checked_count / all_count) * 100)
        else:
            progress_percentage = 0

        context = {
            'not_checked_count': not_checked_count,
            'progress_percentage': progress_percentage,
            'my_memo_ingredients': my_memo_ingredients,
            'my_memo_ingredients_ve': my_memo_ingredients_ve,
            'my_memo_ingredients_me': my_memo_ingredients_me,
            'my_memo_ingredients_ma': my_memo_ingredients_ma,
            'my_memo_ingredients_gr': my_memo_ingredients_gr,
            'my_memo_ingredients_sa': my_memo_ingredients_sa,
            'my_memo_ingredients_mi': my_memo_ingredients_mi,
        }
        return render(request, 'main/memo/memo.html', context)
    return redirect('main:memo')


def add_memo(request):
    ingredients = Ingredient.objects.all().order_by('name')

    search_text = request.GET.get('search_text')

    if search_text:
        ingredients = ingredients.filter(name__contains=search_text)
    else:
        ingredients = ingredients

    context = {
        'ingredients': ingredients,
    }
    return render(request, 'main/memo/add_memo.html', context)


def add_memo_ingredient(request, pk):
    ingredient = Ingredient.objects.get(pk=pk)
    MyMemoIngredient.objects.get_or_create(user=request.user, ingredient=ingredient)
    return redirect('main:memo')


def delete_memo_ingredient(request, pk):
    my_memo_ingredient = MyMemoIngredient.objects.get(pk=pk)
    my_memo_ingredient.delete()
    return redirect('main:memo')


def memo_check(request, pk):
    my_memo_ingredient = MyMemoIngredient.objects.get(pk=pk)
    if my_memo_ingredient.status == 'checked':
        my_memo_ingredient.status = 'not_checked'
        my_memo_ingredient.save()
    else:
        my_memo_ingredient.status = 'checked'
        my_memo_ingredient.save()
    return redirect('main:memo')


def memo_check_clear(request):
    my_memo_ingredients = MyMemoIngredient.objects.filter(user=request.user)
    checked_clear = list()
    for my_memo_ingredient in my_memo_ingredients:
        if my_memo_ingredient.status == 'checked':
            MyStoredIngredient.objects.get_or_create(user=request.user, ingredient=my_memo_ingredient.ingredient)
            checked_clear.append(my_memo_ingredient)
        else:
            pass

    for checked_clear_item in checked_clear:
        checked_clear_item.delete()
    return redirect('main:memo')


def recommendation(request):
    if request.user.is_authenticated:
        my_stored_ingredients = MyStoredIngredient.objects.filter(user=request.user)

        food_all, food_br, food_ve, food_ma, food_me, food_ri, food_ki, food_de = list(), list(), list(), list(), list(), list(), list(), list()
        for my_stored_ingredient in my_stored_ingredients:
            all_food = RecommendedFood.objects.filter(ingredient=my_stored_ingredient.ingredient)

            for food in all_food:
                if food is not None:
                    if food.type == '육수':
                        food_br.append(food)
                    elif food.type == '채소':
                        food_ve.append(food)
                    elif food.type == '해산물':
                        food_ma.append(food)
                    elif food.type == '고기/계란':
                        food_me.append(food)
                    elif food.type == '쌀/밥':
                        food_ri.append(food)
                    elif food.type == '김치/발효':
                        food_ki.append(food)
                    elif food.type == '간식/디저트':
                        food_de.append(food)

        food_all = food_br + food_ve + food_ma + food_me + food_ri + food_ki + food_de

        context = {
            'food_all_set': set(food_all),
            'food_br_set': set(food_br),
            'food_ve_set': set(food_ve),
            'food_ma_set': set(food_ma),
            'food_me_set': set(food_me),
            'food_ri_set': set(food_ri),
            'food_ki_set': set(food_ki),
            'food_de_set': set(food_de),
        }
        return render(request, 'main/recommendation/recommendation.html', context)
    return redirect('main:recommendation')


def like(request, pk):
    recommended_food = RecommendedFood.objects.get(pk=pk)
    if request.user in recommended_food.user.all():
        recommended_food.user.remove(request.user)
    else:
        recommended_food.user.add(request.user)

app/templates/main/recommendation/recipe.html
{% extends 'main/base.html' %}
{% load static %}

{% block style %}
<style>
body {
    background: url('https://images.unsplash.com/photo-1457301473530-d6d4d4d7b824?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=699&q=80') no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    background-size: cover;
    -o-background-size: cover;
}

ol {
    padding: 0;
}

div.d-flex > strong {
    color: #333030;
}

div.d-flex > a {
    color: #ff7473;
}

span.d-block {
    color: #8b8687;
}

div.media-body > p {
    color: #a3a1a1;
}

div.card-body > h6 {
    color: #f9a11b;
}

.border-bottom {
    border-bottom: 1px solid #ffc952 !important;
}



</style>
{% endblock %}

{% block active %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'main:fridge' %}">냉장고 관리</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'main:memo' %}">장보기 메모</a>
</li>
<li class="nav-item active">
    <a class="nav-link" href="{% url 'main:recommendation' %}">추천 메뉴</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'main:store' %}">스토어</a>
</li>
{% endblock %}

{% block content %}
<div class="container">
    <div class="card border-0 shadow my-5">
        <h1 class="px-5 pt-5" style="color: #79bd9a;">{{ food.name }}</h1>
        <div class="card-body px-5 py-3">
            <h3 class="font-weight-light mt-4 mb-0">재료</h3>
            <hr class="my-3">
            <ul class="row text-lg-left list-unstd appyled m-0 p-0">
                <li class="col p-0">
                    {% for ingredient in food_ingredients %}
                    <p class="media pt-2 m-0" style="color: #212529; font-size: 1.4rem !important;">
                        {{ ingredient }}
                        <a href="" style="height: 38px;">
                            <svg class="bi bi-cart-plus mx-4" width="1em" height="1em" viewBox="0 0 16 16"
                                 fill="currentColor"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                      d="M8.5 5a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 .5-.5z"/>
                                <path fill-rule="evenodd"
                                      d="M8 7.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0v-2z"/>
                                <path fill-rule="evenodd"
                                      d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                            </svg>
                        </a>
                    </p>
                    {% endfor %}
                </li>
            </ul>
        </div>

        <div class="card-body px-5 py-3">
            <h3 class="font-weight-light mt-4 mb-0">조리과정</h3>
            <hr class="my-3">
            <ol class="text-lg-left" style="list-style: none;">
                {% for recipe in food_recipe %}
                <p>{{ recipe }}</p>
                {% endfor %}
            </ol>
        </div>

        <div class="card-body px-5 py-3">
            <h6 class="border-bottom border-gray pb-2 mb-0">쿡톡</h6>
            <form class="was-validated" action="{% url 'main:comment-create' pk=food.pk %}" method="post">
                {% csrf_token %}
                <div class="mb-1">
                    <label for="validationTextarea"></label>
                    <textarea class="form-control" id="validationTextarea" name="input_comment"
                              style="background-image: none; border-color: #ffc952;"
                              placeholder="쿡톡 댓글을 남겨주세요" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary btn-sm"
                        style="background-color: #ffc952; border-color: #ffc952;">쿡톡남기기
                </button>
            </form>

            {% if comments %}
            {% for comment in comments %}
            <div class="media text-muted pt-3">
                <!--                <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32"-->
                <!--                     xmlns="http://www.w3.org/2000/svg"-->
                <!--                     preserveAspectRatio="xMidYMid slice" focusable="false" role="img"-->
                <!--                     aria-label="Placeholder: 32x32">-->
                <!--                    <title>Placeholder</title>-->
                <!--                    <rect width="100%" height="100%" fill="#007bff"></rect>-->
                <!--                    <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>-->
                <!--                </svg>-->
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <strong>{{ comment.user.nickname }}</strong>
                        <a href="#">Follow</a>
                    </div>
                    <span class="d-block">{{ comment.comment }}</span>
                    <p class="m-0"><small>{{ comment.created_date }}</small></p>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p class="text-muted mt-2">남긴 쿡톡이 없습니다.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}